"""Recipe notes

Revision ID: 0b03545a1db5
Revises: a4df8e45e6ad
Create Date: 2018-01-31 11:10:01.772386

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b03545a1db5'
down_revision = 'a4df8e45e6ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe', sa.Column('notes', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipe', 'notes')
    # ### end Alembic commands ###
