"""original author

Revision ID: dc55aedc161d
Revises: 0b03545a1db5
Create Date: 2018-01-31 15:40:53.059817

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc55aedc161d'
down_revision = '0b03545a1db5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe', sa.Column('original_author_id', sa.Integer(), nullable=True))
    op.add_column('recipe', sa.Column('original_recipe_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipe', 'original_recipe_id')
    op.drop_column('recipe', 'original_author_id')
    # ### end Alembic commands ###
